export const initialCategories = [
  {
    id: 1,
    name: "🔥 Deals & Combos",
    slug: "deals-and-combos",
    icon: "Flame",
    sortOrder: 1,
    isActive: true,
  },
  {
    id: 2,
    name: "🍕 Gourmet Pizzas",
    slug: "gourmet-pizzas",
    icon: "Pizza",
    sortOrder: 2,
    isActive: true,
  },
  {
    id: 3,
    name: "🍔 Sizzling Burgers",
    slug: "sizzling-burgers",
    icon: "Sandwich",
    sortOrder: 3,
    isActive: true,
  },
  {
    id: 4,
    name: "🍟 Fries & Sides",
    slug: "fries-and-sides",
    icon: "UtensilsCrossed",
    sortOrder: 4,
    isActive: true,
  },
  {
    id: 5,
    name: "🥤 Cold Drinks & Shakes",
    slug: "cold-drinks-and-shakes",
    icon: "CupSoda",
    sortOrder: 5,
    isActive: true,
  },
  {
    id: 6,
    name: "🍝 Pastas",
    slug: "pastas",
    icon: "Utensils",
    sortOrder: 6,
    isActive: true,
  },
  {
    id: 7,
    name: "🥪 Sandwiches",
    slug: "sandwiches",
    icon: "Sandwich",
    sortOrder: 7,
    isActive: true,
  },
];

export const initialMenuItems = [
  // ─────────────────────────────────────────
  // Deals & Combos
  // ─────────────────────────────────────────
  {
    id: 1,
    categoryId: 1,
    name: "Pizzious Mega Feast Deal",
    slug: "pizzious-mega-feast-deal",
    description: "1 Large Gourmet Pizza + 2 Crispy Zinger Burgers + Large Masala Fries + 1.5 Litre Chilled Soft Drink.",
    price: 3499,
    salePrice: 2899,
    images: ["https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=800&auto=format&fit=crop&q=80", "https://images.unsplash.com/photo-1603508102983-99b101395d1a?w=800&auto=format&fit=crop&q=80"],
    isDeal: true,
    dealItems: [
      { name: "1 Large Pizza (Any Flavor)", quantity: 1, description: "13-inch fresh dough pizza" },
      { name: "Crispy Zinger Burgers", quantity: 2, description: "With signature spicy mayo" },
      { name: "Large Masala Fries", quantity: 1, description: "Crispy crinkle-cut fries" },
      { name: "1.5L Chilled Drink", quantity: 1, description: "Coke / Sprite / Fanta" },
    ],
    isActive: true,
    isFeatured: true,
    isBestseller: true,
    stock: 99,
  },
  {
    id: 2,
    categoryId: 1,
    name: "Duo Crunch Combo",
    slug: "duo-crunch-combo",
    description: "2 Crunchy Zinger Burgers + 1 Regular Loaded Pizza + Medium Fries + 2 Soft Drinks (345ml).",
    price: 2199,
    salePrice: 1799,
    images: ["https://images.unsplash.com/photo-1700835880402-434acb82fca9?w=800&auto=format&fit=crop&q=80", "https://images.unsplash.com/photo-1603508102983-99b101395d1a?w=800&auto=format&fit=crop&q=80"],
    isDeal: true,
    dealItems: [
      { name: "Crunchy Zinger Burgers", quantity: 2, description: "Juicy chicken thigh fillet" },
      { name: "Regular Pizza", quantity: 1, description: "9-inch hand tossed" },
      { name: "Medium Fries", quantity: 1, description: "Golden salted fries" },
      { name: "345ml Drinks", quantity: 2, description: "Cold soft drinks" },
    ],
    isActive: true,
    isFeatured: true,
    isBestseller: true,
    stock: 99,
  },
  {
    id: 3,
    categoryId: 1,
    name: "Midnight Snack Attack",
    slug: "midnight-snack-attack",
    description: "1 Smash Beast Beef Burger + 6 Spicy BBQ Wings + Peri Peri Dip + 500ml Drink.",
    price: 1599,
    salePrice: 1299,
    images: ["https://images.unsplash.com/photo-1700835880402-434acb82fca9?w=800&auto=format&fit=crop&q=80", "https://images.unsplash.com/photo-1544241907-f3f1f5ded15a?w=800&auto=format&fit=crop&q=80"],
    isDeal: true,
    dealItems: [
      { name: "Smash Beast Beef Burger", quantity: 1, description: "Double smash patty & cheddar" },
      { name: "Spicy BBQ Wings", quantity: 6, description: "Glazed buffalo BBQ wings" },
      { name: "500ml Drink", quantity: 1, description: "Chilled soda" },
    ],
    isActive: true,
    isFeatured: false,
    isBestseller: true,
    stock: 99,
  },
  {
    id: 21,
    categoryId: 1,
    name: "Family Feast Bonanza",
    slug: "family-feast-bonanza",
    description: "2 Large Pizzas + 4 Smash Burgers + 2 Large Fries + Garlic Bread + 2 x 1.5L Drinks.",
    price: 5999,
    salePrice: 4799,
    images: ["https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=800&auto=format&fit=crop&q=80", "https://images.unsplash.com/photo-1603508102983-99b101395d1a?w=800&auto=format&fit=crop&q=80"],
    isDeal: true,
    dealItems: [
      { name: "Large Pizzas", quantity: 2, description: "Any flavor, 13-inch" },
      { name: "Smash Burgers", quantity: 4, description: "Double beef patty" },
      { name: "Large Fries", quantity: 2, description: "Crispy salted fries" },
      { name: "Garlic Bread", quantity: 1, description: "Herb butter garlic bread" },
      { name: "1.5L Drinks", quantity: 2, description: "Coke / Sprite / Fanta" },
    ],
    isActive: true,
    isFeatured: true,
    isBestseller: true,
    stock: 50,
  },

  // ─────────────────────────────────────────
  // Gourmet Pizzas
  // ─────────────────────────────────────────
  {
    id: 4,
    categoryId: 2,
    name: "Pizzious Crown Crust Specialty",
    slug: "pizzious-crown-crust-specialty",
    description: "Creamy kabab bites stuffed in golden crown crust, spicy smoked chicken tikka, ranch drizzle, sweet corn, black olives, and 100% pure mozzarella.",
    price: 1850,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: true,
    isBestseller: true,
    stock: 50,
  },
  {
    id: 5,
    categoryId: 2,
    name: "Fiery Peri Peri Chicken Pizza",
    slug: "fiery-peri-peri-chicken-pizza",
    description: "Spiced peri-peri grilled chicken chunks, jalapeños, red onions, diced bell peppers, mozzarella, and flaming peri sauce drizzle.",
    price: 1650,
    salePrice: 1450,
    images: ["https://images.unsplash.com/photo-1604382355076-af4b0eb60143?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: true,
    isBestseller: false,
    stock: 50,
  },
  {
    id: 6,
    categoryId: 2,
    name: "Classic Cheesy Pepperoni",
    slug: "classic-cheesy-pepperoni",
    description: "Loaded with crispy halal beef pepperoni slices, rich marinara herb sauce, and stretchy double mozzarella cheese blend.",
    price: 1550,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1628840042765-356cda07504e?w=800&auto=format&fit=crop&q=80", "https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: false,
    isBestseller: true,
    stock: 60,
  },
  {
    id: 7,
    categoryId: 2,
    name: "Chicken Fajita Delight",
    slug: "chicken-fajita-delight",
    description: "Marinated Mexican fajita chicken, caramelized onions, crisp green bell peppers, mushrooms, and melted gouda-mozzarella cheese.",
    price: 1490,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: false,
    isBestseller: false,
    stock: 45,
  },
  {
    id: 17,
    categoryId: 2,
    name: "Tandoori Chicken Supreme",
    slug: "tandoori-chicken-supreme",
    description: "Tandoori chicken strips, roasted peppers, onions, leeks, and smoky garlic sauce with signature mozzarella.",
    price: 1750,
    salePrice: 1550,
    images: ["https://images.unsplash.com/photo-1552539618-7eec9b4d1796?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: true,
    isBestseller: true,
    stock: 42,
  },
  {
    id: 22,
    categoryId: 2,
    name: "BBQ Smoked Chicken Pizza",
    slug: "bbq-smoked-chicken-pizza",
    description: "Slow-smoked chicken chunks, sweet BBQ base sauce, red onion rings, roasted corn, and stretchy mozzarella on hand-tossed dough.",
    price: 1700,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: true,
    isBestseller: true,
    stock: 55,
  },
  {
    id: 23,
    categoryId: 2,
    name: "Margherita Classico",
    slug: "margherita-classico",
    description: "Stone-baked thin crust with San Marzano tomato sauce, fresh basil leaves, extra virgin olive oil drizzle, and premium buffalo mozzarella.",
    price: 1199,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: false,
    isBestseller: true,
    stock: 70,
  },
  {
    id: 24,
    categoryId: 2,
    name: "Spicy Beef Bolognese Pizza",
    slug: "spicy-beef-bolognese-pizza",
    description: "Slow-cooked spiced beef mince bolognese, caramelized onions, fresh jalapeños, crushed red pepper, and double cheese blend.",
    price: 1780,
    salePrice: 1580,
    images: ["https://images.unsplash.com/photo-1548369937-47519962c11a?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: true,
    isBestseller: false,
    stock: 40,
  },
  {
    id: 25,
    categoryId: 2,
    name: "Veggie Supreme Pizza",
    slug: "veggie-supreme-pizza",
    description: "Garden-fresh mushrooms, bell peppers, black olives, cherry tomatoes, spinach, red onion, and mozzarella on herb tomato base.",
    price: 1350,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: false,
    isBestseller: false,
    stock: 35,
  },

  // ─────────────────────────────────────────
  // Sizzling Burgers
  // ─────────────────────────────────────────
  {
    id: 54,
    categoryId: 2,
    name: "Smoky Tandoori Chicken Pizza",
    slug: "smoky-tandoori-chicken-pizza",
    description: "Tandoori chicken, roasted peppers, red onion, mozzarella, and a smoky tikka drizzle on our signature hand-tossed base.",
    price: 1690,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: false,
    isBestseller: true,
    stock: 55,
  },
  {
    id: 55,
    categoryId: 2,
    name: "Four Cheese Garden Pizza",
    slug: "four-cheese-garden-pizza",
    description: "Mozzarella, cheddar, parmesan, cream cheese, mushrooms, olives, and herbs over a rich roasted garlic base.",
    price: 1590,
    salePrice: 1440,
    images: ["https://images.unsplash.com/photo-1579751626657-72bc17010498?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: false,
    isBestseller: false,
    stock: 45,
  },
  {
    id: 56,
    categoryId: 2,
    name: "Pepperoni Firecracker Pizza",
    slug: "pepperoni-firecracker-pizza",
    description: "Spicy beef pepperoni, jalapeños, mozzarella, chili oil, and roasted garlic for a bold, fiery finish.",
    price: 1750,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1593560708920-61dd98c8c4c5?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: false,
    isBestseller: true,
    stock: 50,
  },
  {
    id: 57,
    categoryId: 2,
    name: "Creamy Malai Chicken Pizza",
    slug: "creamy-malai-chicken-pizza",
    description: "Creamy malai chicken, sweet corn, mushrooms, mozzarella, and fresh coriander on a creamy herb sauce.",
    price: 1720,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: false,
    isBestseller: false,
    stock: 40,
  },

  // ─────────────────────────────────────────
  // Sizzling Burgers
  // ─────────────────────────────────────────
  {
    id: 58,
    categoryId: 3,
    name: "Firehouse Jalapeno Smash",
    slug: "firehouse-jalapeno-smash",
    description: "Double smashed beef patties, pepper jack, crispy jalapeños, pickles, and smoky firehouse sauce in a brioche bun.",
    price: 1090,
    salePrice: 950,
    images: ["https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: false,
    isBestseller: true,
    stock: 60,
  },
  {
    id: 59,
    categoryId: 3,
    name: "Mushroom Swiss Melt",
    slug: "mushroom-swiss-melt",
    description: "Juicy beef patty, sauteed mushrooms, Swiss cheese, caramelized onions, and creamy pepper sauce.",
    price: 980,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: false,
    isBestseller: false,
    stock: 50,
  },
  {
    id: 60,
    categoryId: 3,
    name: "Crispy Buffalo Chicken Burger",
    slug: "crispy-buffalo-chicken-burger",
    description: "Crispy chicken fillet tossed in buffalo sauce with ranch slaw, cheddar, and crunchy lettuce.",
    price: 840,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1615297928064-24977384d0da?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: false,
    isBestseller: true,
    stock: 65,
  },
  {
    id: 61,
    categoryId: 3,
    name: "BBQ Onion Ring Burger",
    slug: "bbq-onion-ring-burger",
    description: "Chargrilled beef patty, cheddar, crispy onion rings, barbecue glaze, lettuce, and signature burger sauce.",
    price: 920,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: false,
    isBestseller: false,
    stock: 55,
  },

  // ─────────────────────────────────────────
  // Cold Drinks & Shakes
  // ─────────────────────────────────────────
  {
    id: 62,
    categoryId: 5,
    name: "Pepsi 1.5 Litre",
    slug: "pepsi-1-5-litre",
    description: "Ice-cold Pepsi with its bold cola taste, perfect for sharing with a hot meal.",
    price: 220,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1629203849820-fdd70d49c38e?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: false,
    isBestseller: true,
    stock: 150,
  },
  {
    id: 63,
    categoryId: 5,
    name: "Coca-Cola 1.5 Litre",
    slug: "coca-cola-1-5-litre",
    description: "Classic Coca-Cola served chilled, with the refreshing taste customers know and love.",
    price: 220,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1554866585-cd94860890b7?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: false,
    isBestseller: true,
    stock: 150,
  },
  {
    id: 64,
    categoryId: 5,
    name: "7UP 1.5 Litre",
    slug: "7up-1-5-litre",
    description: "Crisp, lemon-lime 7UP served ice-cold alongside your favorite Pizzious meal.",
    price: 220,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1625772299848-391b6a87d7b3?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: false,
    isBestseller: false,
    stock: 150,
  },
  {
    id: 65,
    categoryId: 5,
    name: "Sprite 1.5 Litre",
    slug: "sprite-1-5-litre",
    description: "Bright, lemon-lime Sprite served chilled for a clean, sparkling refreshment.",
    price: 220,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1629203851122-3726ecdf080e?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: false,
    isBestseller: false,
    stock: 150,
  },
  {
    id: 66,
    categoryId: 5,
    name: "Fanta Orange 1.5 Litre",
    slug: "fanta-orange-1-5-litre",
    description: "Fanta Orange served cold with a vibrant citrus taste and lively fizz.",
    price: 220,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1624517452488-04869289c4ca?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: false,
    isBestseller: false,
    stock: 150,
  },

  // ─────────────────────────────────────────
  // More Sizzling Burgers
  // ─────────────────────────────────────────
  {
    id: 8,
    categoryId: 3,
    name: "The Beast Double Smash Burger",
    slug: "the-beast-double-smash-burger",
    description: "Two 100% prime beef patties smashed with grilled onions, double American cheddar cheese, dill pickles, and secret Pizzious burger sauce on a butter-toasted brioche bun.",
    price: 990,
    salePrice: 850,
    images: ["https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=800&auto=format&fit=crop&q=80", "https://images.unsplash.com/photo-1603508102983-99b101395d1a?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: true,
    isBestseller: true,
    stock: 80,
  },
  {
    id: 9,
    categoryId: 3,
    name: "Mega Crunch Zinger",
    slug: "mega-crunch-zinger",
    description: "Extra large crispy whole chicken breast fillet marinated in 11 secret herbs, iceberg lettuce, melted cheese slice, and garlic mayo.",
    price: 690,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: true,
    isBestseller: true,
    stock: 90,
  },
  {
    id: 10,
    categoryId: 3,
    name: "Smoky BBQ Bacon Melt Burger",
    slug: "smoky-bbq-bacon-melt-burger",
    description: "Charbroiled beef patty, crispy halal beef strips, onion rings, smoky hickory BBQ sauce, and pepper jack cheese.",
    price: 1050,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: false,
    isBestseller: false,
    stock: 50,
  },
  {
    id: 18,
    categoryId: 3,
    name: "Crispy Chicken Ranch Burger",
    slug: "crispy-chicken-ranch-burger",
    description: "Crunchy fried chicken fillet, cheddar, lettuce, pickled onions, and creamy ranch drizzle on a toasted bun.",
    price: 760,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1520072959219-c595dc870360?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: false,
    isBestseller: true,
    stock: 70,
  },
  {
    id: 26,
    categoryId: 3,
    name: "Tower Stacker Cheese Burger",
    slug: "tower-stacker-cheese-burger",
    description: "Triple-stacked beef patties, triple cheese melt, caramelized onions, fried egg, tomato, and special stacker sauce in a sesame bun.",
    price: 1290,
    salePrice: 1099,
    images: ["https://images.unsplash.com/photo-1561758033-d89a9ad46330?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: true,
    isBestseller: true,
    stock: 60,
  },
  {
    id: 27,
    categoryId: 3,
    name: "Spicy Jalapeño Crunch Burger",
    slug: "spicy-jalapeno-crunch-burger",
    description: "Crispy chicken fillet, fresh jalapeño slices, pepper jack cheese, shredded lettuce, and fiery sriracha mayo in a toasted brioche bun.",
    price: 790,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: true,
    isBestseller: false,
    stock: 65,
  },
  {
    id: 28,
    categoryId: 3,
    name: "Classic Beef Cheeseburger",
    slug: "classic-beef-cheeseburger",
    description: "100% halal beef patty, American cheddar, fresh tomato, crisp lettuce, pickles, and classic Pizzious special sauce on a soft bun.",
    price: 590,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: false,
    isBestseller: true,
    stock: 100,
  },

  // ─────────────────────────────────────────
  // Fries & Sides
  // ─────────────────────────────────────────
  {
    id: 12,
    categoryId: 4,
    name: "Pizzious Loaded Cheese Fries",
    slug: "pizzious-loaded-cheese-fries",
    description: "Golden crinkle-cut fries smothered in hot cheddar cheese sauce, crispy chicken bits, jalapeño slices, and smoky chipotle mayo.",
    price: 650,
    salePrice: 550,
    images: ["https://images.unsplash.com/photo-1585109649139-366815a0d713?w=800&auto=format&fit=crop&q=80", "https://images.unsplash.com/photo-1485962398705-ef6a13c41e8f?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: true,
    isBestseller: true,
    stock: 75,
  },
  {
    id: 13,
    categoryId: 4,
    name: "Flaming Buffalo Wings (8 Pcs)",
    slug: "flaming-buffalo-wings-8-pcs",
    description: "8 pieces of juicy crispy fried wings coated in tangy spicy Louisiana buffalo sauce served with cool garlic dip.",
    price: 790,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: false,
    isBestseller: true,
    stock: 60,
  },
  {
    id: 19,
    categoryId: 4,
    name: "Cheesy Garlic Fries Supreme",
    slug: "cheesy-garlic-fries-supreme",
    description: "Golden fries tossed with roasted garlic butter, cheddar melt, parmesan, and a hint of herb seasoning.",
    price: 620,
    salePrice: 540,
    images: ["https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: true,
    isBestseller: true,
    stock: 90,
  },
  {
    id: 29,
    categoryId: 4,
    name: "Masala Fries",
    slug: "masala-fries",
    description: "Crispy golden fries dusted with a secret blend of chaat masala, chili flakes, cumin, and dried mango powder. Addictively tangy.",
    price: 350,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1576107232684-1279f390859f?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: true,
    isBestseller: true,
    stock: 120,
  },
  {
    id: 30,
    categoryId: 4,
    name: "Peri Peri Fries",
    slug: "peri-peri-fries",
    description: "Thick-cut fries tossed in our signature peri-peri spice blend, finished with fresh lemon zest and parsley. Fiery and addictive.",
    price: 390,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: false,
    isBestseller: false,
    stock: 100,
  },

  // ─────────────────────────────────────────
  // Cold Drinks & Shakes
  // ─────────────────────────────────────────
  {
    id: 14,
    categoryId: 5,
    name: "Belgian Chocolate Fudge Shake",
    slug: "belgian-chocolate-fudge-shake",
    description: "Thick premium soft ice cream blended with dark Belgian chocolate fudge, topped with whipped cream and chocolate shavings.",
    price: 550,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: false,
    isBestseller: true,
    stock: 100,
  },
  {
    id: 15,
    categoryId: 5,
    name: "Chilled Soft Drink (1.5 Litre)",
    slug: "chilled-soft-drink-1-5-litre",
    description: "Choice of Coca-Cola, Sprite, Fanta, or Diet Coke — ice-cold and refreshing.",
    price: 250,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=800&auto=format&fit=crop&q=80", "https://images.unsplash.com/photo-1544241907-f3f1f5ded15a?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: false,
    isBestseller: false,
    stock: 150,
  },
  {
    id: 16,
    categoryId: 5,
    name: "Mint Margarita Slush",
    slug: "mint-margarita-slush",
    description: "Refreshing crushed ice slush with fresh mint leaves, lemon juice, black salt, and sparkling soda.",
    price: 390,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: false,
    isBestseller: false,
    stock: 80,
  },
  {
    id: 20,
    categoryId: 5,
    name: "Vanilla Oreo Shake",
    slug: "vanilla-oreo-shake",
    description: "Cold creamy vanilla shake blended with Oreo crumble, topped with whipped cream and chocolate biscuit dust.",
    price: 520,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: false,
    isBestseller: true,
    stock: 60,
  },
  {
    id: 31,
    categoryId: 5,
    name: "Strawberry Banana Shake",
    slug: "strawberry-banana-shake",
    description: "Fresh strawberries and ripe bananas blended with premium vanilla ice cream and whole milk into a thick, refreshing shake.",
    price: 490,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: true,
    isBestseller: false,
    stock: 80,
  },
  {
    id: 32,
    categoryId: 5,
    name: "Mango Lassi Delight",
    slug: "mango-lassi-delight",
    description: "Chilled desi mango pulp blended with thick yogurt, a pinch of cardamom, and rose water. A refreshing Pakistani classic.",
    price: 350,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: true,
    isBestseller: true,
    stock: 90,
  },

  // ─────────────────────────────────────────
  // Pastas
  // ─────────────────────────────────────────
  {
    id: 11,
    categoryId: 6,
    name: "Creamy Chicken Alfredo Pasta",
    slug: "creamy-chicken-alfredo-pasta",
    description: "Fettuccine pasta tossed in rich parmesan garlic cream sauce, grilled chicken strips, sautéed mushrooms, and herbs.",
    price: 980,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1645112411341-6c4fd023714a?w=800&auto=format&fit=crop&q=80", "https://images.unsplash.com/photo-1552056776-9b5657118ca4?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: false,
    isBestseller: true,
    stock: 40,
  },
  {
    id: 33,
    categoryId: 6,
    name: "Spicy Arrabbiata Penne",
    slug: "spicy-arrabbiata-penne",
    description: "Al dente penne pasta in a fiery arrabbiata sauce of crushed tomatoes, fresh garlic, chili flakes, and fresh basil.",
    price: 790,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: true,
    isBestseller: false,
    stock: 50,
  },
  {
    id: 34,
    categoryId: 6,
    name: "Pink Rose Sauce Pasta",
    slug: "pink-rose-sauce-pasta",
    description: "Penne tossed in a velvety blend of tomato and cream sauce, sun-dried tomatoes, grilled chicken, and parmesan shavings.",
    price: 950,
    salePrice: 850,
    images: ["https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: true,
    isBestseller: true,
    stock: 45,
  },
  {
    id: 35,
    categoryId: 6,
    name: "Carbonara Spaghetti",
    slug: "carbonara-spaghetti",
    description: "Classic Roman-style spaghetti carbonara with egg yolk, pecorino, black pepper, and crispy halal beef bacon bits.",
    price: 1050,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: false,
    isBestseller: false,
    stock: 35,
  },

  // ─────────────────────────────────────────
  // Sandwiches
  // ─────────────────────────────────────────
  {
    id: 36,
    categoryId: 7,
    name: "Grilled Chicken Club Sandwich",
    slug: "grilled-chicken-club-sandwich",
    description: "Juicy grilled chicken breast, crispy lettuce, ripe tomato, cheese slice, and honey mustard mayo stacked in toasted multi-grain bread.",
    price: 590,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1539252554453-80ab65ce3586?w=800&auto=format&fit=crop&q=80", "https://images.unsplash.com/photo-1540713434306-58505cf1b6fc?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: true,
    isBestseller: true,
    stock: 80,
  },
  {
    id: 37,
    categoryId: 7,
    name: "Beef Steak Submarine",
    slug: "beef-steak-submarine",
    description: "Thinly sliced seared beef steak, caramelized onions, green peppers, provolone cheese, and Philly-style chipotle sauce in a hoagie roll.",
    price: 850,
    salePrice: 750,
    images: ["https://images.unsplash.com/photo-1521305916504-4a1121188589?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: true,
    isBestseller: true,
    stock: 60,
  },
  {
    id: 38,
    categoryId: 7,
    name: "Crispy Zinger Wrap",
    slug: "crispy-zinger-wrap",
    description: "Spicy crispy fried chicken strip, shredded lettuce, tomato salsa, cheese, and garlic mayo wrapped in a warm flour tortilla.",
    price: 490,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1553909489-cd47e0907980?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: false,
    isBestseller: true,
    stock: 90,
  },
  {
    id: 39,
    categoryId: 7,
    name: "Veggie Pesto Panini",
    slug: "veggie-pesto-panini",
    description: "Pressed panini with house pesto, grilled zucchini, roasted red peppers, black olives, mozzarella, and sun-dried tomatoes.",
    price: 550,
    salePrice: null,
    images: ["https://images.unsplash.com/photo-1528736235302-52922df5c122?w=800&auto=format&fit=crop&q=80"],
    isDeal: false,
    isActive: true,
    isFeatured: false,
    isBestseller: false,
    stock: 45,
  },
  {
    id: 40,
    categoryId: 7,
    name: "Smoked Turkey Melt Sandwich",
    slug: "smoked-turkey-melt-sandwich",
    description: "Layers of smoked turkey breast, melted cheddar, crisp lettuce, tomato, and honey-mustard on toasted sourdough.",
    price: 620,
    salePrice: null,
    images: [
      "https://images.unsplash.com/photo-1540713434306-58505cf1b6fc?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1539252554453-80ab65ce3586?w=800&auto=format&fit=crop&q=80",
    ],
    isDeal: false,
    isActive: true,
    isFeatured: false,
    isBestseller: false,
    stock: 55,
  },

  // ─────────────────────────────────────────
  // New Additions — More Pizza, Burgers, Loaded Fries & Cold Drinks
  // ─────────────────────────────────────────
  {
    id: 41,
    categoryId: 2,
    name: "Loaded Meat Feast Pizza",
    slug: "loaded-meat-feast-pizza",
    description: "Triple meat overload — beef pepperoni, spiced chicken tikka chunks, and smoked beef sausage, layered on double mozzarella and rich tomato base.",
    price: 1890,
    salePrice: 1690,
    images: [
      "https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1628840042765-356cda07504e?w=800&auto=format&fit=crop&q=80",
    ],
    isDeal: false,
    isActive: true,
    isFeatured: true,
    isBestseller: false,
    stock: 40,
  },
  {
    id: 42,
    categoryId: 3,
    name: "Ultimate Bacon Smash Stack",
    slug: "ultimate-bacon-smash-stack",
    description: "Double smashed beef patties, crispy beef bacon, double cheddar, caramelized onions, and smoky burger sauce on a toasted brioche bun.",
    price: 1090,
    salePrice: null,
    images: [
      "https://images.unsplash.com/photo-1603508102983-99b101395d1a?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=800&auto=format&fit=crop&q=80",
    ],
    isDeal: false,
    isActive: true,
    isFeatured: true,
    isBestseller: false,
    stock: 55,
  },
  {
    id: 43,
    categoryId: 4,
    name: "Bacon Ranch Loaded Fries",
    slug: "bacon-ranch-loaded-fries",
    description: "Crispy golden fries piled with melted cheddar sauce, crumbled beef bacon, creamy ranch drizzle, and chopped spring onions.",
    price: 690,
    salePrice: 590,
    images: [
      "https://images.unsplash.com/photo-1485962398705-ef6a13c41e8f?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1585109649139-366815a0d713?w=800&auto=format&fit=crop&q=80",
    ],
    isDeal: false,
    isActive: true,
    isFeatured: true,
    isBestseller: true,
    stock: 70,
  },
  {
    id: 44,
    categoryId: 5,
    name: "Classic Iced Cola Float",
    slug: "classic-iced-cola-float",
    description: "Ice-cold cola over a scoop of creamy vanilla soft-serve — a fizzy, refreshing classic float.",
    price: 320,
    salePrice: null,
    images: [
      "https://images.unsplash.com/photo-1544241907-f3f1f5ded15a?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=800&auto=format&fit=crop&q=80",
    ],
    isDeal: false,
    isActive: true,
    isFeatured: false,
    isBestseller: false,
    stock: 100,
  },
];

export const initialStoreSettings = {
  id: 1,
  storeName: "Pizzious",
  logoType: "svg" as const,
  logoUrl: "",
  phone: "0325 1020222",
  whatsappNumber: "+923251020222",
  email: "pizzious@gmail.com",
  address: "Madina Market, F-8, Kahuta, District Rawalpindi, Punjab, Pakistan",
  deliveryFee: 150,
  freeDeliveryThreshold: 2500,
  isDeliveryActive: true,
  easyPaisaTitle: "Pizzious Official Wallet",
  easyPaisaNumber: "03001234567",
  meezanTitle: "Pizzious Fast Food Pvt Ltd",
  meezanIban: "PK42MEZN0001234567890123",
  meezanAccount: "0123456789012",
  sadaPayTitle: "Pizzious Fast Food",
  sadaPayNumber: "03001234567",
  jazzCashTitle: "Pizzious Official Wallet",
  jazzCashNumber: "03001234567",
  payPalEmail: "payments@pizzious.com",
  payPalInstructions: "Send transfer to payments@pizzious.com or paypal.me/pizzious and enter your Transaction ID or sender PayPal email at checkout.",
  manualPaymentInstructions: "Please transfer the exact order amount to any of our official accounts above and enter your Transaction ID or sender phone number at checkout for instant verification.",
  announcementText: "🔥 FREE Delivery on orders over Rs. 2,500! Freshly baked and sizzling hot to your door.",
  isAnnouncementActive: true,
  heroTitle: "Crave the Crunch. Taste the Flame.",
  heroSubtitle: "Handcrafted gourmet pizzas, sizzling smash burgers, and irresistible combo deals delivered piping hot to your doorstep in 30 minutes.",
  heroImageUrl: null,
};